name: "pre-release"

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Pre-release"
    runs-on: "ubuntu-latest"
    container: ghcr.io/opencs-ontology/ci-worker:main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: opencs

      - name: "Package ontology"
        run: python /app/package.py opencs package dev
        
      - name: "Install Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: "Infer additional assertions"
        run: |
          bash /app/inference/infer_assertions.sh
          touch inferred_assertions.ttl
          bash /app/inference/ofn_to_ttl.sh inferred_assertions.ofn inferred.ttl
          rm output_opencs.ttl opencs2.ttl
          gzip inferred.ttl
          mv inferred.ttl.gz package/inferred.ttl.gz

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development build"
          files: package/*

      - name: Prepare files to be committed to another repository
        run: |
          mkdir output_files
          gzip -cd package/opencs.ttl.gz > output_files/opencs.ttl
          gzip -cd package/opencs.rdf.gz > output_files/opencs.rdf
          gzip -cd package/opencs.nt.gz > output_files/opencs.nt

      - name: "Generate pages for Github Pages repository"
        run: python /app/generate_pages.py dev $GITHUB_REPOSITORY output_files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Prepare Github Pages static files"
        run: |
          mv output_files/page.md output_files/index.md

      - name: "Push files for dev version"
        uses: "cpina/github-action-push-to-another-repository@main"
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'output_files'
          destination-github-username: 'opencs-ontology'
          destination-repository-name: 'opencs-ontology.github.io'
          user-name: ci-worker
          target-directory: /releases/dev/
          target-branch: main
