name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged release"
    runs-on: "ubuntu-latest"
    container: ghcr.io/opencs-ontology/ci-worker:main

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          path: opencs

      - name: "Package ontology"
        run: python /app/package.py opencs package "$GITHUB_REF_NAME"

      - name: "Infer additional assertions"
        run: |
          bash /app/inference/infer_assertions.sh
          touch inferred_assertions.ttl
          bash /app/inference/ofn_to_ttl.sh inferred_assertions.ofn inferred_assertions.ttl
          rm output_opencs.ttl opencs2.ttl
          gzip inferred_assertions.ttl
          mv inferred_assertions.ttl.gz package/inferred.ttl.gz

      - uses: "softprops/action-gh-release@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{  github.ref_name }}"
          prerelease: false
          files: package/*

      - name: "Prepare ontology files to be committed to another repository"
        run: |
          mkdir output_files tag stable versions
          gzip -cd package/opencs.ttl.gz > output_files/opencs.ttl
          gzip -cd package/opencs.rdf.gz > output_files/opencs.rdf
          gzip -cd package/opencs.nt.gz > output_files/opencs.nt
          cp output_files/opencs.* tag
          cp output_files/opencs.* stable

      - name: "Prepare data for ontology web browser"
        run: |
          python /app/prepare_browser_data.py stable/opencs.ttl browser

      - name: "Set target directory variable for current tag version"
        run: |
          TAG_PATH=releases/${GITHUB_REF_NAME#v}
          echo "TAG_PATH=$TAG_PATH" >> $GITHUB_ENV

      - name: "Generate pages for Github Pages repository"
        run: python /app/generate_pages.py ${GITHUB_REF_NAME#v} $GITHUB_REPOSITORY output_files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Prepare Github Pages static files"
        run: |
          cp output_files/page.md tag/index.md
          cp output_files/page.md stable/index.md
          cp output_files/versions.md versions/index.md

      - name: "Set up git"
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: "Push files for current tag version"
        run: |
          git clone git@github.com:OpenCS-ontology/OpenCS-ontology.github.io.git
          cp -a tag/. OpenCS-ontology.github.io/$TAG_PATH
          cp -a stable/. OpenCS-ontology.github.io/releases/stable/
          cp -a versions/. OpenCS-ontology.github.io/releases/versions/ 
          cp -a browser/. OpenCS-ontology.github.io/assets/data/
          cd OpenCS-ontology.github.io
          git config user.name "opencs-ontology"
          git config user.email "ci-worker@opencs-ontology.github.io"
          git add $TAG_PATH/* releases/stable/* releases/versions/* assets/*
          git commit -m "New tagged release: ${GITHUB_REF_NAME#v}"
          git push
