name: "validate"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: "Validate ontology"
    runs-on: "ubuntu-latest"
    container: ghcr.io/opencs-ontology/ci-worker:main

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          path: opencs

      - name: "Validate ontology with SHACL"
        run: bash /app/validate_jena.sh

      - name: "Upload validation report"
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          name: validation_report
          path: package/validation_report.ttl
